### ISSUE TITLE
remote alerting possible?

### ISSUE THREAD

**Issue by IrishMoss** [xperiments-in/xtouch#11]
## Feature Description

Due to some print reliability issues while in cloud mode, i've been forced to switch to LAN mode on my p1p.  
(I know you mentioned lan-mode issues with firmware 1.04, but it looks like v1.04.01 fixed those issues, as i'm using lan mode successfully with that version)

Anyway, while lan mode is working fine, it's disabling of the handy app connectivity means i can no longer get remote alerts from the printer.  In particular for filament runout.  
Would there be any way to use or configure the xtouch to send alerts (maybe SMS alerts?) to a phone for things like filament runout?

Thanks

## Justification

Replacing functionality that bambu explicitly blocks when in lan mode.

## Suggested Implementation (if you have one)

unsure.

## Screenshots or Examples (if applicable)

N/A

**Comment by xperiments** [comment]
Not actually, SMS sending is not free BTW. 
Actually is out of scope of this project.
Thanks!!
