### ISSUE TITLE
Is this project dead?  Last commit was 3 months ago!

### ISSUE THREAD

**Issue by Misterke** [xperiments-in/xtouch#112]
As there is no mention of any discord channel or other communication channel where this question could be settled, I'm resorting to putting it down here as a feature request ...

This project seemed so promising and full of potential, but the past 3 months it seems to have died down.  There's no lack of issues or feature requests getting raised, but I get the impression the author (and so far apparently sole contributor) has jumped ship.

Can anyone confirm or counter that idea?  And if confirmed, is there some other developer eager to take over with his fork?

**Comment by xperiments** [comment]
Project is not dead. Discord channel is listed at top of the readme.
