### ISSUE TITLE
asking for version 0.9.58 

### ISSUE THREAD

**Issue by SKYKR** [xperiments-in/xtouch#114]
I tried compiling 0.9.57 and it seemed not working...

It does infinite reboot on the board...

Will there be source version 0.9.58, the same version as online installer?

**Comment by Sascha27** [comment]
Habe das selbe Problem nach der Installation des Online-Installationsprogram
LOG zeigt ständigen Reboot an und Bildschirm bleibt schwarz

**Comment by xperiments** [comment]
All latest Code is un git. I cant support builds outside off mine

**Comment by xperiments** [comment]
@SKYKR versions from git can vary... all the release ones are in xtouch-bin github
