### ISSUE TITLE
Wiring of temperature sensor

### ISSUE THREAD

**Issue by obause** [xperiments-in/xtouch#115]
As the JST connector on the ESP32 is a 4-pin connector, but the temperature sensor only has 3 pins it would be helpful to get some information about the wiring how it gets connected. Thanks!

**Comment by MULAWI** [comment]
https://github.com/xperiments-in/xtouch/blob/main/docs/temperature-sensor.md

**Comment by MULAWI** [comment]
worked fine for me

**Comment by KevinFairgrieve** [comment]
Also works for me.
