### ISSUE TITLE
Online Flash erfolgreich aber schwarzes Bild und ständige reboots

### ISSUE THREAD

**Issue by Sascha27** [xperiments-in/xtouch#123]
Nach 
![XTouch Web Installer](https://github.com/xperiments-in/xtouch/assets/138030427/f4923281-ddbc-42d2-a8cb-5dcc79fe8427)
dem Online Flash bootet Board ständig neu und Display bleibt aus

**Comment by xperiments** [comment]
First, please write in english as is the oficial lang used in xtouch. (I am spanish)
Second I suppose you are using a 2.4 board.
I am correct?

2.4 Boards ar not supported, only 2.8 Resistive ones
