### ISSUE TITLE
JWT parsing error

### ISSUE THREAD

**Issue by Loadie150** [xperiments-in/xtouch#132]
**Describe the bug**
My P1s has been turned off for 1 week, when I hooked it back up today I read not able to connect. I went in and reinstalled both the .json file and firmware from the Xtouch installer page. When the ESP32 boots up it reads, connecting, then connected, then processing JWT token, then finally FATAL BBl JWT parsing error. This just cycles over and over again.

**To Reproduce**

**Expected behavior**

**Screenshots**

**XTOUCH (please complete the following information):**
 - FW: [not sure, latest one on github site]

**Printers (please complete the following information):**
 - Device: [ P1S]
 - FW Version [e.g. 01.06.00.00]
-  AMS units: [2]

**Additional context**
Not sure what to do ?

**Comment by Loadie150** [comment]
I also formatted the SD card to FAT32 before redoing everything.

**Comment by xperiments** [comment]
Have you made the config here ?

https://xperiments.in/xtouch-bin/config.html

**Comment by Loadie150** [comment]
Yes I did. I originally did the notepad way, but that didn’t work. So I reformatted the SD card and used the link then the xtouch uploader.

**Comment by telematique89** [comment]
I have the Same issue.

**Comment by xperiments** [comment]
Have y 2FA enabled, if so disable it

**Comment by telematique89** [comment]
It was the 2FA. thanks !

**Comment by xperiments** [comment]
Great

**Comment by crossfun** [comment]
I have the same Problem with the Firmware 0.9.103
2FA is disabled.

**Comment by xperiments** [comment]
And you have entered your bambu password or your gmail password? Needs to be from bambu account

**Comment by crossfun** [comment]
I have entered my Bambu Login. GMX Mail and the Bambu Password.

**Comment by Loadie150** [comment]
> Have y 2FA enabled, if so disable it

What’s 2FA?

**Comment by Loadie150** [comment]
Problem resolved! Fat finger stupid mistake. Error on password, lol.. Still don't know what 2FA is though.

**Comment by xperiments** [comment]
2fa two factor authentication...

So the process of receiving a Code or have An app for that that validates
IS you

**Comment by crossfun** [comment]
I double-checked my 2FA disabled twice, formatted the SD card again, and created a new configuration file. The password I entered was copied and pasted. I am still receiving the same error.

**Comment by xperiments** [comment]
Only thing I can say is come to Discord where I am mostly avaliable all time and just ask
So we can try to see whats the problem live...
Anyone reported not able to connect after solving password reset and disabling 2FA
BTW you are in China?
Thats the only servers I was unable to test

**Comment by xperiments** [comment]
Closed in 0.9.115

A lot of thanks to @crossfun for his test and support!!
