### ISSUE TITLE
WIF connected but can not Getting accessToken from Bambu Cloud

### ISSUE THREAD

**Issue by all4fun** [xperiments-in/xtouch#135]
**Describe the bug**
WIF connected but can not Getting accessToken from Bambu Cloud.
I made sure I entered all the correct passwords and tried to reset them.

**To Reproduce**
1. flash latest FW
2. gen config.json
3. insert SD card to ESP32-2432S028
4. See error from Logs...

**Expected behavior**

**Screenshots**

**XTOUCH (please complete the following information):**
 - FW: latest

error log detail:
------------------------------------------------
[XTouch][SD] Reading JSON file: /config.json
Getting accessToken from Bambu Cloud
[  8249][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():273]: (-9984) X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
[  8264][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -9984
Received error: -1
deserializeJson() failed: EmptyInput
ets Jul 29 2019 12:21:46

**Comment by xperiments** [comment]
Have you disabled 2FA?

I close it as is mostly a bad config.

### Important Update for XTouch Users

We are excited to announce a major update to XTouch! As part of this update, you will now need to use your Bambulab account to log in to the cloud.

We are currently in the process of updating the firmware (FW). Meanwhile, you can prepare your account and set up a password if needed.

**Note:** Users registered with a Gmail account do not have a password set up. To resolve this, please follow these steps:

1. **Go to the Bambulab main page and click login.**
2. **Click on "Forgot my password."**
3. **Follow the instructions to set a new password for your BambuLab account.**

**Disable 2FA if enabled**

Additionally, users will need to generate a new `config.json` file to replace the old `wifi.json` file. 

To create this `config.json` file, please use the online config tool located at:

https://xperiments.in/xtouch-bin/config.html
