### ISSUE TITLE
Is the code Arduino IDE compatible?

### ISSUE THREAD

**Issue by Ap1965** [xperiments-in/xtouch#141]
>Hello, good work on that project. Can i use the Sourcecode on Arduino IDE?
I try to rename the main.cpp to main.ino and the compilation show error on IDE 1.8.x and on IDE 2.3.x.

I want to add some addidional values from my homeautomation, temp, Humidity etc.

**Comment by xperiments** [comment]
No, is only compatible w PlattformIO
