### ISSUE TITLE
Again FATAL BBL JWT PARSING ERROR since today 

### ISSUE THREAD

**Issue by Sascha27** [xperiments-in/xtouch#142]
FATAL BBL JWT PARSING ERROR since today

Since today I have the problem that Xtouch is stuck in a loop.

Even another firmware update with firmware.bin did not solve the problem.

Printer P1S

Firmware 01.06.00.00

Xtouch tries this all the time:
-WiFi connected
-Processing JWT Token
-FATAL BBL JWT PARSING ERROR

**Comment by xperiments** [comment]
Fixed in v0.9.133

Do a OTA update

**Comment by xperiments** [comment]
How you generate the config.json

Not tested but w this chars needs to be ok
