### ISSUE TITLE
Cannot update, not via OTA nor via file on the SD card

### ISSUE THREAD

**Issue by riochicken** [xperiments-in/xtouch#143]
When I turn on OTA updates, it does a 5 time download of the firmware, stops at 100%, says the download is invalid and starts over. When I manually download the .bin file and put it on the SD card, turn on the xtouch, it says the .bin file is corrupted and deletes the .bin file...

Currently running: v0.9.58
Using a p1s with 1 AMS

Thank you in advance!

Richard

**Comment by xperiments** [comment]
You are coming from a too old version. You need to reinstall from web installer.
Come on to Discord if problem continues.

**Comment by riochicken** [comment]
Mmmmm I already had a feeling that this could have been the issue... Thanks! Will update somewhere today... :)
