### ISSUE TITLE
Fatal BBLJWT parsing error loop

### ISSUE THREAD

**Issue by reedy** [xperiments-in/xtouch#145]
**Describe the bug**
Device continually retries, fails and reboots

**To Reproduce**
1. Plug in the power...

**Expected behavior**
Device to boot

**Screenshots**
https://github.com/xperiments-in/xtouch/assets/67615/c0e55fc3-6d81-4016-896a-5dd997ba0eaf

**XTOUCH (please complete the following information):**
 - FW: not sure as device won't boot

**Printers (please complete the following information):**
 - Device: P1S
 - FW Version 01.06.00.00
-  AMS units: 1

**Additional context**

**Comment by xperiments** [comment]
This is a known bug related to an old version. 
Please Reinstall From WEB
FORMAT SD <- IMPERATIVE
