### ISSUE TITLE
Multiple OTA failures in a row

### ISSUE THREAD

**Issue by reedy** [xperiments-in/xtouch#146]
**Describe the bug**
On boot, the device tries to OTA. Fails multiple times (no idea why).

Seen before #145

**To Reproduce**
1. Power on the device

**Expected behavior**
If there is an OTA, the device should be able to download and load it successfully

**Screenshots**

**XTOUCH (please complete the following information):**
 - FW: unsure as device won't boot due to #145

**Printers (please complete the following information):**
 - Device: P1S
 - FW Version 01.06.00.00
-  AMS units: 1

**Additional context**

**Comment by xperiments** [comment]
This is a known bug related to an old version.
Please Reinstall From WEB
FORMAT SD <- IMPERATIVE
