### ISSUE TITLE
Black screen on reboot or power cycling

### ISSUE THREAD

**Issue by kittyprime** [xperiments-in/xtouch#149]
**Describe the bug**

**To Reproduce**
1. Go to settings and click reboot
2. Power off printer and power on again 

**Expected behavior**
Normal boot sequence with prompts saying logging into BBL
**Screenshots**
Upon rebooting, xtouch screens loads but then a black screen occurs. No prompts to say loading into BBL cloud 

**XTOUCH (please complete the following information):**
 - FW: latest OTA 140

**Printers (please complete the following information):**
 - Device: P1S
 - FW Version 01.06.00.00
-  AMS units:1

**Additional context**
Have tried increasing  cold boot to max
When I wipe the SD and do a fresh install with firmware.bin it loads fine. As soon as I either reboot on the X touch or power cycle at the P1S switch it reboots to black screen.

**Comment by xperiments** [comment]
Come to discord so we can check it better.
BTW can y check with another sd card and brand?
