### ISSUE TITLE
Support for LAN-Only

### ISSUE THREAD

**Issue by TobyStoe** [xperiments-in/xtouch#150]
**Describe the bug**
Since I dont have my printer connected to BambuLabs-Cloud. The Startup is in a infinity-loop

**To Reproduce**
1. Have no Printers on the Cloud
2. Boot xtouch
3. LOOP

**Expected behavior**
If no printer is found in the cloud, there should be a option to search local (or make it a setting in the config.json)

**Screenshots**

**XTOUCH (please complete the following information):**
 - current

**Printers (please complete the following information):**
 - Device: P1S

LOG:

`[XTOUCH][CONNECTION] Connecting to WiFi ..
[XTOUCH][CONNECTION] Connected to the WiFi network with IP: 192.168.1.116
[XTouch][SD] Reading JSON file: /config.json
Getting accessToken from Bambu Cloud
Getting device list from Bambu Cloud
[XTouch][SD] Reading JSON file: /xtouch/printer.json
null[XTouch][SD] Writting JSON file: /xtouch/printer.json
No devices found in Bambu Cloud
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
[XTouch][SCREEN] Setup
[   676][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x40114124 arg=0x3ffbfdb8
XTouch][SD] SD Card Type: [XTouch][SD] SDSC
[XTouch][SD] SD Card Size: 1876MB
[XTouch][SD] Reading JSON file: /xtouch/settings.json
[XTouch][FS] Checking for touch config
[XTouch][TOUCH] Load from disk
[XTouch][SD] Reading JSON file: /config.json
[XTOUCH][CONNECTION] Connecting to WiFi ..
[XTOUCH][CONNECTION] Connected to the WiFi network with IP: 192.168.1.116
[XTouch][SD] Reading JSON file: /config.json
Getting accessToken from Bambu Cloud
Getting device list from Bambu Cloud
[XTouch][SD] Reading JSON file: /xtouch/printer.json
null[XTouch][SD] Writting JSON file: /xtouch/printer.json
No devices found in Bambu Cloud
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
[XTouch][SCREEN] Setup
[   676][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x40114124 arg=0x3ffbfdb8
XTouch][SD] SD Card Type: [XTouch][SD] SDSC
[XTouch][SD] SD Card Size: 1876MB
[XTouch][SD] Reading JSON file: /xtouch/settings.json
[XTouch][FS] Checking for touch config
[XTouch][TOUCH] Load from disk
[XTouch][SD] Reading JSON file: /config.json
[XTOUCH][CONNECTION] Connecting to WiFi ..
[XTOUCH][CONNECTION] Connected to the WiFi network with IP: 192.168.1.116
[XTouch][SD] Reading JSON file: /config.json
Getting accessToken from Bambu Cloud
Getting device list from Bambu Cloud
[XTouch][SD] Reading JSON file: /xtouch/printer.json
null[XTouch][SD] Writting JSON file: /xtouch/printer.json
No devices found in Bambu Cloud
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
[XTouch][SCREEN] Setup
[   676][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x40114124 arg=0x3ffbfdb8
XTouch][SD] SD Card Type: [XTouch][SD] SDSC
[XTouch][SD] SD Card Size: 1876MB
[XTouch][SD] Reading JSON file: /xtouch/settings.json
[XTouch][FS] Checking for touch config
[XTouch][TOUCH] Load from disk
[XTouch][SD] Reading JSON file: /config.json
[XTOUCH][CONNECTION] Connecting to WiFi ..
[XTOUCH][CONNECTION] Connected to the WiFi network with IP: 192.168.1.116
[XTouch][SD] Reading JSON file: /config.json
Getting accessToken from Bambu Cloud
Getting device list from Bambu Cloud
[XTouch][SD] Reading JSON file: /xtouch/printer.json
null[XTouch][SD] Writting JSON file: /xtouch/printer.json
No devices found in Bambu Cloud
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
[XTouch][SCREEN] Setup
[   676][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x40114124 arg=0x3ffbfdb8
XTouch][SD] SD Card Type: [XTouch][SD] SDSC
[XTouch][SD] SD Card Size: 1876MB
[XTouch][SD] Reading JSON file: /xtouch/settings.json
[XTouch][FS] Checking for touch config
[XTouch][TOUCH] Load from disk
[XTouch][SD] Reading JSON file: /config.json
[XTOUCH][CONNECTION] Connecting to WiFi ..
[XTOUCH][CONNECTION] Connected to the WiFi network with IP: 192.168.1.116
[XTouch][SD] Reading JSON file: /config.json
Getting accessToken from Bambu Cloud
Getting device list from Bambu Cloud
[XTouch][SD] Reading JSON file: /xtouch/printer.json
null[XTouch][SD] Writting JSON file: /xtouch/printer.json
No devices found in Bambu Cloud
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
[XTouch][SCREEN] Setup
[   676][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x40114124 arg=0x3ffbfdb8
XTouch][SD] SD Card Type: [XTouch][SD] SDSC
[XTouch][SD] SD Card Size: 1876MB
[XTouch][SD] Reading JSON file: /xtouch/settings.json
[XTouch][FS] Checking for touch config
[XTouch][TOUCH] Load from disk
[XTouch][SD] Reading JSON file: /config.json
[XTOUCH][CONNECTION] Connecting to WiFi ..
[XTOUCH][CONNECTION] Connected to the WiFi network with IP: 192.168.1.116
[XTouch][SD] Reading JSON file: /config.json
Getting accessToken from Bambu Cloud
Getting device list from Bambu Cloud
[XTouch][SD] Reading JSON file: /xtouch/printer.json
null[XTouch][SD] Writting JSON file: /xtouch/printer.json
No devices found in Bambu Cloud
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
[XTouch][SCREEN] Setup
[   676][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x40114124 arg=0x3ffbfdb8
XTouch][SD] SD Card Type: [XTouch][SD] SDSC
[XTouch][SD] SD Card Size: 1876MB
[XTouch][SD] Reading JSON file: /xtouch/settings.json
[XTouch][FS] Checking for touch config
[XTouch][TOUCH] Load from disk
[XTouch][SD] Reading JSON file: /config.json
[XTOUCH][CONNECTION] Connecting to WiFi ..
[XTOUCH][CONNECTION] Connected to the WiFi network with IP: 192.168.1.116
[XTouch][SD] Reading JSON file: /config.json
Getting accessToken from Bambu Cloud
Getting device list from Bambu Cloud
[XTouch][SD] Reading JSON file: /xtouch/printer.json`

**Comment by xperiments** [comment]
Until new direcctions from BBL I will stuck in Cloud Mode.
We will see the changes BBL say coming on August...
I am sorry but is hard to maintain two branches with all latest BBL changes...

Refer to this meanwhile to return to a version woking in lan mode

https://github.com/xperiments-in/xtouch/issues/130
