### ISSUE TITLE
Add 5V LED control via ESP32 board. 

### ISSUE THREAD

**Issue by thias15** [xperiments-in/xtouch#152]
## Feature Description

Would be great to have the option to control external 5V LEDs from the ESP32. 

One option would be to trigger along with the printer LED toggle. Another option would be a dedicated menu that allows changing color, brightness, etc.

**Comment by xperiments** [comment]
No, sorry.... where you will taking the power?
There are other project like BBLed for that.
I will be integrating it in next 5 inch later 2.8
