### ISSUE TITLE
Battery monitoring 

### ISSUE THREAD

**Issue by kubert96** [xperiments-in/xtouch#154]
## Feature Description

Hello, 
firs of all. Great project. Realy good job. 

Woud it will be posible to add Battery monitoring on some pins of ESP? 

## Justification

I have been runing this https://www.printables.com/cs/model/582641-bambu-lab-p1pp1sx1c-18650-portable-display-xtouch 
case as my daili driver. But i dont know how much is battery charged. 

It woud be perfect if i coud monitor battery in top bar. That hase Wifi, Camera, Timelapse icon. 

You alredy have I2C temperature. (Witch in this portable version i "cant" use. And port is free to use with diferent I2C device)
So i think. It woud be easy add suport for something like: MAX17043

https://simplyexplained.com/blog/max17043-battery-monitoring-done-right-arduino-esp32/

Thank you so much.

**Comment by xperiments** [comment]
Not applicable
