### ISSUE TITLE
This error appears in the image. I did all the required steps and there is no solution. Some say that the card version is not supported.

### ISSUE THREAD

**Issue by saifoo81** [xperiments-in/xtouch#156]
![٢٠٢٤٠٨٠١_٢٣٠٠٣٣.jpg](https://github.com/user-attachments/assets/13506ab5-4f10-470a-ada2-33e9516191e3)

![٢٠٢٤٠٧٣١_١٤٣٣٣٨.jpg](https://github.com/user-attachments/assets/0bf92d41-8cc3-4fb0-8e49-47a718da8cdc)

**Comment by sonicmingit** [comment]
I had the same problem, found out it was the wrong password for the bambu account, changed it again and it was fine. I changed the email address to my cell phone number.

**Comment by Bobcobra** [comment]
What is the fix for this? This has happened 3 times now and I'm tired of removing it to fix and reload.

**Comment by xperiments** [comment]
> What is the fix for this? This has happened 3 times now and I'm tired of removing it to fix and reload.

Install from zero from web installer
