### ISSUE TITLE
Touchscreen trouble,After installing, my xtouch does not respond to touch. It displays changes such as turning on the printer's light or changing the nozzle temperature, but I cannot control anything from the screen. The touch screen works and calibration can be performed. What this is about ?

### ISSUE THREAD

**Issue by lukasz2194** [xperiments-in/xtouch#157]
## Feature Description

[Detailed description of the new feature you're requesting]

## Justification

[Reasons why you believe this feature would be useful]

## Suggested Implementation (if you have one)

[Ideas on how the feature could be implemented]

## Screenshots or Examples (if applicable)

[Attach screenshots or examples if relevant]

**Comment by lukasz2194** [comment]
After installing, my xtouch does not respond to touch. It displays changes such as turning on the printer's light or changing the nozzle temperature, but I cannot control anything from the screen. The touch screen works and calibration can be performed. What this is about ?

**Comment by lukasz2194** [comment]
Solution : Recalibrate touchscreen propertly :P

**Comment by jazzyboy** [comment]
I'm in the same case : the install was Ok, the appairing to the printer Ok, the screen display the xtouch desktop, but no interactions is possible with the screen.
The colors seems to be very light and not the same as i could see on the youtube channels (less contrast)
![IMG_20241008_001344943](https://github.com/user-attachments/assets/4f7cfa3c-b2c4-4c66-966f-8b4dd4f63b1c)

**Comment by lukasz2194** [comment]
Try to reinstall and calibrate touchscreen again after installation

**Comment by Quanghoster** [comment]
Seeing the same thing here.  Did anyone found a solution?  Reinstalling didn't resolve

**Comment by Quanghoster** [comment]
> Seeing the same thing here. Did anyone found a solution? Reinstalling didn't resolve

My bad - I was touching the x in the text instead of the one in the top left of the screen when calibrating, lol.  It works perfectly now I'm not being an idiot
