### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Just-messing-around** [xperiments-in/xtouch#16]
Created the json file and installed the SD card. Drivers are working and show in device manager. Launched the website and have now tried ~20 times to install code. No errors shown and appears to write to ESP32 without incident. Never get the splash screen nor a screen to calibrate (plus sign) screen. When opening console window, see this error:

Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

**Comment by xperiments** [comment]
Come to discord, and comment you problem. Are you using the 2.8 screen? we need more info.
Please verify your model is a 2.8 and not a 2.4 3.5 or 4.3

I close by no because we need more info. reopen if needed
