### ISSUE TITLE
Message to go to http://(local ip) - which then asks for a Bambu Lab Verification Code

### ISSUE THREAD

**Issue by Sebba1976** [xperiments-in/xtouch#166]
As of yesterday my XTOUCH is asking me to go to http://(local ip) - which then asks for a Bambu Lab Verification Code - Check your email for code.

The problem is that I haven'
![Uploading thumbnail_IMG_1993.jpg…]()
t received an email with a code.

**Comment by Captain0Kangaroo** [comment]
I'm also getting this issue as of 2 days ago.

**Comment by tuc0w** [comment]
I just updated to the current version, got the msg and also received the mail.
Did you check your Bambu account that it has the correct email address set? Maybe check your junk folder?

**Comment by umeiko** [comment]
china has no email and have to login with phone number, which can't recive the message

**Comment by dannutu** [comment]
Hmmm, it seems that I missed the x-touch version that also worked in local LAN mode by just a week... the current one clearly wants to connect to Bambu's "cloud" servers. Which I'm having none of, sorry.

**Comment by xperiments** [comment]
China bug resolved
