### ISSUE TITLE
not working since the last update

### ISSUE THREAD

**Issue by poli27** [xperiments-in/xtouch#171]
Connect to http://x.x.x.x 
the display connection stops here... the two-step identification is not activated in the bambu account, and yet confirmation codes are coming, what is going on and what is the solution to this?

**Comment by xperiments** [comment]
Connect to http://x.x.x.x/

**Comment by poli27** [comment]
the x indicates the IP address, I just typed it in... that's how far the display goes!

**Comment by Fredzp1s** [comment]
Hello, I have install Xtouch on board this day and it don't connect to bambu printer, only say Go to HTTP:/192.168.1.10
What does i made after ? is there a bambu restriction ?

**Comment by xperiments** [comment]
@Fredzp1s You need to goto the address it shows in the screen with a browser

Check your email... you will receive a bbl verification. code

Them enter this code in the page


PD: If you received a lot of codes today by ex... Wait some hours as they maybe blocked temporally you the access
