### ISSUE TITLE
Still Can't provision

### ISSUE THREAD

**Issue by rubyredrick** [xperiments-in/xtouch#176]
I followed the new installation process using the Chrome extension in the recently updated README.  The extension fails with the message:

          An error occurred provisioning the device. Please check that the
          entered IP is correct
        
For what it might be worth, my SSID is a space separated list of words.  The device is not showing up in my routers list of attached devices, so it looks like it never made a DHCP request.

**Comment by xperiments** [comment]
Read the instructions carefully. Is well explained there....

**Comment by rubyredrick** [comment]
Sorry, but there's another issue opened by another user, the extension doesn't seem to work on Mac

**Comment by xperiments** [comment]
@rubyredrick come to discord, show me... Does not "work" is not an issue...

- What
- When
- Where

You (all) think I am magician and know the bugs you have beforehand...
It is developed in MAC, tested on other macs.... So I need more info to be able to help
