### ISSUE TITLE
My XTOUCH has started showing the message Missing provisioning.json

### ISSUE THREAD

**Issue by Sebba1976** [xperiments-in/xtouch#177]
**Describe the bug**
My XTOUCH has started showing the message Missing provisioning.json

**To Reproduce**
Simply on startup

**XTOUCH (please complete the following information):**
 - FW: Latest. I assume this is due to an OTA firmware update.

**Printers (please complete the following information):**
 - Device: P1S
 - FW Version 01.06.01.02
-  AMS units:1

**Additional context**
Started this afternoon. I have loaded a new config.json to see if this would fix it, but it hasn't.

**Comment by xperiments** [comment]
Software was updates vía OTA. Check the new instructions on git

**Comment by mpregione** [comment]
I am having the same problem.

**Comment by tbc0309** [comment]
Me too……Log in to……

**Comment by bowlesjk** [comment]
I am having the same problem.  Updated firmware yesterday and been unable to correct the issue.  Running P1S, Chrome (Win 10)

**Comment by xperiments** [comment]
Guys when you use the plugin are you in that moment at the bambulab.com
Page.. not the shop... And logged in?

**Comment by Sebba1976** [comment]
Yes, I'm on the bambulab.com site. Logged in.

![image](https://github.com/user-attachments/assets/5d8dffd1-255d-4754-9267-da99b20153f2)

**Comment by mpregione** [comment]
Yes. On Bambu.com

**Comment by xperiments** [comment]
Will need them you just come to Discord, where we can see ion more depth

**Comment by xperiments** [comment]
Anyway I am mostly sure you are not correct logged in

<img width="530" alt="image" src="https://github.com/user-attachments/assets/4f027792-7cd9-4487-91ba-4c08d7749de5">

In the main page you need to see you avatar icon... 
Sometimes when login it opens a new window, that will not work... Needs to be in the main window.

If you logged and not icon shown, just reload the page

**Comment by xperiments** [comment]
If any of you here now... I will be on discord for at least 1h since now
https://discord.gg/yRNWJj55

**Comment by Sebba1976** [comment]
You'd be incorrect. I am definitely logged in:

![image](https://github.com/user-attachments/assets/45984001-ba81-4915-969e-7af4592e74ca)

**Comment by Sebba1976** [comment]
I'm currently on discord

**Comment by Sebba1976** [comment]
I've resolved this issue. With the bambulab.com site open in your browser, f you right-hand click on the extension and then select 'this can read and change site data' and select the middle option 'On bambulab.com' it brings the menu up.

![image](https://github.com/user-attachments/assets/f7651a80-b275-44d5-a5e4-339fa3c749ce)

**Comment by xperiments** [comment]
@Sebba1976 sorry for deleting... but that is not correct and will make the extension not work properly 

I just update the extension to 1.3.1

Update it

And try from 0

This update will solve most of the "miss" interpretation USERs are doing w the instructions...

I say bambulab.com

Never say the STORE

Now it will be a lot more clear

**Comment by bowlesjk** [comment]
Thanks I have it working again. Sent from Mail for Windows From: Pedro CasaubonSent: Wednesday, November 27, 2024 12:11 AMTo: xperiments-in/xtouchCc: bowlesjk; CommentSubject: Re: [xperiments-in/xtouch] My XTOUCH has started showing the message Missing provisioning.json (Issue ***@***.*** sorry for deleting... but that is not correct and will make the extension not work properlyI just update the extension to 1.3.1Update itAnd try from 0This update will solve most of the "miss" interpretation USERs are doing w the instructions...I say bambulab.comNever say the STORENow it will be a lot more clear—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by krummrey** [comment]
I just ran into the same problem. Did a complete install, recalibrated the corners and am stuck without the provisioning.json.
I'm logged on to bambu lab and printig.

**Comment by xperiments** [comment]
@krummrey Installation is new, refer to the readme

**Comment by sonicmingit** [comment]
Having the same problem, upgrading the latest version of firmware won't fix it, feel like it's a device issue, i have two esp screens.
1. Put the problematic device tf card into another device, it can start normally
2. Put the original normal device tf card into this problematic device, the same Missing provisioning.json appears.

**Comment by xperiments** [comment]
Seems a HW failure
