### ISSUE TITLE
create provisioning. json

### ISSUE THREAD

**Issue by tbc0309** [xperiments-in/xtouch#178]
I am still unable to use Chrome Extension version 1.3.2, so I manually created provisioning. json and tested OK

[provisioning.json](https://github.com/user-attachments/files/17936081/provisioning.json)

```
{
  "ssid": "xxx",
  "pwd": "12345678",
  "cloud-email": "xxx",
  "cloud-region": "China", 
  "cloud-username": "u_12345678",
  "cloud-authToken": "xxx"
}
```

cloud-region  is China or World
cloud-email is phone number(China )、email(World )

cloud-username is u_uidStr (browser page press F12 to open DevTools)

![1732718484200](https://github.com/user-attachments/assets/4245c8a5-17a5-4ec6-9090-f32ae0a61769)

cloud-authToken  (browser page press F12 to open DevTools)

![1732718652711](https://github.com/user-attachments/assets/c8d8cde8-11aa-4a97-99da-61305f2ed08f)

**Comment by Quacker01-sys** [comment]
Hi!

I could really use some hand-holding on this stuff. I'm using our P1S as a production machine in a small business. We love the Xtouch screen but we foolishly updated our P1S and now it's not working. I've followed what you did with the provisioning file up until I got to "cloud-authToken" I don't even know what browser page that is so I can't find the token to finish the file. Can you please help? TIA!

**Comment by xperiments** [comment]
@Quacker01-sys come on discord and give more info

**Comment by Midyew59** [comment]
Attempted to follow your guide.  uidstr is not returning any results when searched for.

**Comment by tbc0309** [comment]
> Attempted to follow your guide. uidstr is not returning any results when searched for.

login then open:

World https://bambulab.com/api/v1/iot-service/api/user/project

China  https://bambulab.cn/api/v1/iot-service/api/user/project

**Comment by Midyew59** [comment]
That got me a little further!

Now the screen says to provision at the IP address I would expect.  Upon visiting that IP address though nothing happens.  Just the Xtouch logo appears on the screen.  But, your information helped make some progress.  I just gotta sit down and start at square one now I think.  Man this would be much easier if the darn Extension would work like it is supposed to lol.

Thanks for the help!

**Comment by tbc0309** [comment]
> That got me a little further!
> 
> Now the screen says to provision at the IP address I would expect. Upon visiting that IP address though nothing happens. Just the Xtouch logo appears on the screen. But, your information helped make some progress. I just gotta sit down and start at square one now I think. Man this would be much easier if the darn Extension would work like it is supposed to lol.
> 
> Thanks for the help!

This is the operation according to the developer's Google Chrome Extension process, but the extension is currently unavailable, so for now, we will manually create provisioning. json ourselves.

**Comment by xperiments** [comment]
@tbc0309 The extension is avaliable is working for other china ppl

**Comment by xperiments** [comment]
Fixed. Update your extensions

**Comment by Haggy38** [comment]
No idea what to do, Im on Mac

**Comment by Haggy38** [comment]
cloud-email is phone number(China )???
