### ISSUE TITLE
Your ESP32-S3 board is not supported.

### ISSUE THREAD

**Issue by BillsWorkbench** [xperiments-in/xtouch#179]
when trying to install using the xtouch Web Installed I get "Your ESP32-S3 board is not supported."

I purchased the 5" board from the link on your main github page.

**Comment by xperiments** [comment]
Come to discord. 5 inch is not released ATM. We can inform better there

**Comment by Nitmare64** [comment]
> Come to discord. 5 inch is not released ATM. We can inform better there

I have the same exact issue. No help on discord for me at the moment
