### ISSUE TITLE
Install on ESP32 S3

### ISSUE THREAD

**Issue by Dobs0001** [xperiments-in/xtouch#20]
Will there be a version for ESP32 S3?

**Comment by xperiments** [comment]
The 5inch version. But I can confirm nothing.

**Comment by Dobs0001** [comment]
I have a 5 inch version with ESP 32 S3 left and would like to use it. Hence the question.

**Comment by xperiments** [comment]
I see. It will be a 5inch version in the future... but board is not defined
etc...
