### ISSUE TITLE
Printer statistics

### ISSUE THREAD

**Issue by michaltulach** [xperiments-in/xtouch#23]
## Feature Description

There could be a statistics table somewhere in settings bar. In this statistics table there would be some information about total extruded filament in meters and in grams, total print time and number of completed and cancelled print jobs.

## Justification

It would help to visualise the statistics of each printer and the printer wear. I would also help while having a 3D printer farm.

## Suggested Implementation (if you have one)

There could be just a bar in setting where the statistics would be.

**Comment by xperiments** [comment]
This feature maybe will be but in another app for farms. 
No sure when when it will come...
