### ISSUE TITLE
Add Makerfabs ESP32 S3 Parallel TFT Support

### ISSUE THREAD

**Issue by 1josh13** [xperiments-in/xtouch#24]
## Feature Description

Add support for the Makerfabs ESP32 S3 parallel touch screen 

https://github.com/Makerfabs/Makerfabs-ESP32-S3-Parallel-TFT-with-Touch

## Justification

Broaden support for other boards. 

## Suggested Implementation (if you have one)

The examples in the repo linked above have some driver files using LovyanGFX 
https://github.com/Makerfabs/Makerfabs-ESP32-S3-Parallel-TFT-with-Touch/blob/main/example/ESP32S3_SGP30_WEBSERVER_V1.2/S3_Parallel16_ili9488.h

While I am not experienced with c++ and new to esp32, I can find my way around a code base, along with having the hardware already, I would love to support testing.

**Comment by xperiments** [comment]
Actually porting to multiple devices = multiply bugs x effort.  Atm I will stay with the 2.8 and work in the 5inch (TBD) version now.

Feel free to make your own fork I will be happy to see some advances!!

Thanks!!!
