### ISSUE TITLE
[XTouch][SD] Error Reading JSON File: /xtouch/printer-pair.json

### ISSUE THREAD

**Issue by MarkusMuenster** [xperiments-in/xtouch#27]
Hallo ich habe ein Problem.
bekomme immer diese meldung
[XTouch][SD] Error Reading JSON File: /xtouch/printer-pair.json

was kann ich machen?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**XTOUCH (please complete the following information):**
 - FW: [e.g. 1.0.0]

**Printers (please complete the following information):**
 - Device: [e.g. P1S]
 - FW Version [e.g. xx.xx.xx]
-  AMS units:[e.g. 1]

**Additional context**

**Comment by xperiments** [comment]
Please come on DIscord channel and explain better your problem. With this info I can't do nothing. Thanks
