### ISSUE TITLE
Chamber Temperature Sensor Calibration

### ISSUE THREAD

**Issue by mike1808** [xperiments-in/xtouch#28]
## Feature Description

Add an ability to offset the temperature sensor to calibrate it. 

## Justification

The sensor I got from the link are offset by 2-3 degrees. I checked the temperature using other thermometer and the sensor connected to xtouch is offset and linearly goes up and down.

## Suggested Implementation (if you have one)

Allow adding positive or negative offset to the temperature.

**Comment by xperiments** [comment]
Need to check. Not sure is actually helpful

**Comment by TheDuffman85** [comment]
A offset setting in a Json file would be sufficient. Should be a one time configuration after assembly, right?

**Comment by xperiments** [comment]
Yes, I will take care of it next week
