### ISSUE TITLE
Stop all movements button

### ISSUE THREAD

**Issue by mike1808** [xperiments-in/xtouch#29]
## Feature Description

Add a button which will stop all active movements when moving build plate or tool head. I'm not sure if there's such a command in firmware but if there's one it'll be nice to have.

## Justification

Sometimes, you might hit a wrong direction button or just want to abort the homing. The only way to do it now is to shut off the printer.

**Comment by xperiments** [comment]
This modifies the normal behaviour of the printer. Also is not posible, after the command is sent not stop...
