### ISSUE TITLE
xtouch keeps prompting to select the printer

### ISSUE THREAD

**Issue by mike1808** [xperiments-in/xtouch#30]
**Describe the bug**
From time to time when I check on xtouch I see the printer selection prompt.

**To Reproduce**
N/A
Unfortunately, I'm unable to provide repro steps. 

**Additional context**

**Comment by xperiments** [comment]
This is mostly related to wifi reconnections. And mostly to DHCP changes. Please check your wifi router settings.

Closing ATM. Reopen if needed, but please try to confirm before opening a bug in discord channel

**Comment by mike1808** [comment]
I have checked all the logs and the IP addresses of xtouch and the printer doesn't change. I also fixed the address and it still has same issues.
I'd like to keep the discussion in GitHub so if other have similar issues they can find it through search engines.

**Comment by xperiments** [comment]
Have you checked with the latest version of today?
