### ISSUE TITLE
Does not resume print properly

### ISSUE THREAD

**Issue by s3anami** [xperiments-in/xtouch#36]
I**Describe the bug**
I selected resume print from the screen after replacing my filament, the printer proceeded to crash itself into all the prints bending the hot end and then proceeded to smash against the back left corner of the printer repeatedly attempting to home or something.

**To Reproduce**
Load Filament button
Confirm
Click Resume Print

**Expected behavior**
To resume printing properly

**Screenshots**

**XTOUCH (please complete the following information):**
 - FW: Latest just updated

**Printers (please complete the following information):**
 - Device: P1P upgraded to P1S
 - FW Version Latest
-  AMS units: 0

**Comment by kenkamm** [comment]
Is this still an issue? Scary...

**Comment by xperiments** [comment]
@s3anami Can you check with the latest firmware? Thanks

**Comment by xperiments** [comment]
I will close as I think is a dupplicate of #47 that is already solved. Feel free to reopen if needed
