### ISSUE TITLE
Try to display liveview on the local lan network

### ISSUE THREAD

**Issue by Error-106** [xperiments-in/xtouch#42]
## Feature Description

Try to display the printer's camera image on the local LAN network(liveview)

## Justification

My printer is in the living room and my xtourch screen is in the bedroom.
I want to view it remotely.
Can you try to acquire camera images within a LAN like Bambu Studio?

## Suggested Implementation (if you have one)

[The Bambu Wiki](https://wiki.bambulab.com/en/p1/troubleshooting/wifi-bt-liveview) mentions that the camera image transmission within the LAN uses ports 1990 2021 and 6000.
Port 6000 appears to be being used to transmit images.

## Screenshots or Examples (if applicable)

[Attach screenshots or examples if relevant]

**Comment by xperiments** [comment]
Not in the scope of this project
