### ISSUE TITLE
Text on the search printer screen can be dragged up or down

### ISSUE THREAD

**Issue by Error-106** [xperiments-in/xtouch#43]
**Describe the bug**
Text on the search printer screen can be dragged up or down.

**To Reproduce**
1. Go to search printer screen
2. Drag up or down

**Expected behavior**

**Screenshots**

**XTOUCH (please complete the following information):**
 - FW: 0.9.24

**Printers (please complete the following information):**
 - Device: P1S
 - FW Version: 01.04.02.00
-  AMS units: None

**Additional context**

**Comment by xperiments** [comment]
This is a normal bahaviour... As you can have more than a printer
