### ISSUE TITLE
Modify the input method of the hibernation setting item

### ISSUE THREAD

**Issue by Error-106** [xperiments-in/xtouch#44]
## Feature Description

Modify the hibernation setting to virtual keyboard input (like entering a binding code)

## Justification

The required sleep time can be set precisely

## Suggested Implementation (if you have one)

[Ideas on how the feature could be implemented]

## Screenshots or Examples (if applicable)

[Attach screenshots or examples if relevant]

**Comment by xperiments** [comment]
No, too much user clicks... Not needed... KISS principle
