### ISSUE TITLE
Screen Flash

### ISSUE THREAD

**Issue by carlosdesedas** [xperiments-in/xtouch#45]
## Feature Description

Hace the xtouch screen flash to call user attention depending on the error

## Justification

Bambu Handy app is not reliable to sending error notifications

## Suggested Implementation (if you have one)

Have a section where you can toggle on/off error type flashes... for example:
AMS Feed error:  have the complete screen flash red every x seconds (continuously until user intervention)
Retraction error:  have the complete screen flash green every x seconds (continuously until user intervention)
Filament error:  have the complete screen flash white every x seconds (continuously until user intervention)
AND SO ON....

this should be able to be toggled on/off and set how many seconds between flashes and/or duration of the actual flash (let it be on until user intervention).

This way you could be sitting away from the printer and SEE the screen flash if there's an error.  also works if you have a camera pointing at the direction of the printer and can remotely see if the screen is flashing.  

SORT of what is done here https://github.com/DutchDevelop/BLLEDController but use the xtouch screen as the indicator itself...

A beeping sound could be done also as a toggle with this feature...

## Screenshots or Examples (if applicable)

[Attach screenshots or examples if relevant]

**Comment by xperiments** [comment]
I will not implement it ATM, better create better integration with BBLED
