### ISSUE TITLE
Request: WS2812B Chamber LED stripe integration

### ISSUE THREAD

**Issue by Elektroarzt** [xperiments-in/xtouch#51]
## Feature Description
After bying a P1S, the first thing is to change the display. Second is installing a bright chamber light as the original Bambu Lab is more a toy than a light you like to have at your 3D printer. I'm always using a torch to see what's going on, which is annoying.

## Justification
All information is available in current firmware of xtouch. I'm sure there is a strong demand for this feature.

## Suggested Implementation (if you have one)
Would be great to have a WS2812B LED stripe integrated in xtouch with e.g. the following features:
- color white: parallel on / off with the original Bambu Lab chamber light
- color red: error during print
- color green: print ended successfully

Maybe some like the colors and some find the white light sufficient, so an option would be great therefor.

Hardware could be wired to the header P3 marked as "Extended IO". It carries 3 GPIO Pins along with GND. WS2812B stripes needs just one GPIO and GND.

LED riser could be taken from [printables](https://www.printables.com/de/model/365027-bambulab-top-glass-riser-4-cob-led-remix-with-led-/comments)

## Screenshots or Examples (if applicable)
If someone is interested in implementing the firmware part, I could provide an electrical and mechanical solution containing cable management in the riser (remix), power supply and housing.

**Comment by xperiments** [comment]
Hello, 

We don't have more IO ports free... we already use io22 / io27

I bet better go with https://github.com/DutchDevelop/BLLEDController
