### ISSUE TITLE
When printer is off then on - Stuck on pair printer screen until checked pressed

### ISSUE THREAD

**Issue by parrothd** [xperiments-in/xtouch#52]
xtouch is not plugged into printer - Independent power supply
Turn the printer off for some period of time.
Xtouch screen goes to pair printer screen
Turn printer on
Xtouch stays on pair printer screen even though printer is on

It would be nice if the Xtouch just kept trying to reconnect to the printer automatically.

**Comment by xperiments** [comment]
Hi

I see your point but is not posible actually

For example who other ppl w more than one printer, what printer to select?
