### ISSUE TITLE
OTA Update failing

### ISSUE THREAD

**Issue by RichMicek** [xperiments-in/xtouch#54]
When performing the OTA update the xtouch starts the download, gets to around 50% and then says verifying and fails.  It does retries this 5 times then shuts off the OTA update.  It appears that the verify process only allows so much time for the download to complete and it's not enough.

**Comment by fdebeer** [comment]
same here. have to do a lot of tries before it really updates. server capacity maybe?

**Comment by xperiments** [comment]
That's not a bug. Actually it tries 5 times because it can't download it correctly. So it disables OTA. Check your wifi range etc... ESP32 is wifi error prone...
