### ISSUE TITLE
Cannot install XTouch

### ISSUE THREAD

**Issue by euroflyer** [xperiments-in/xtouch#56]
I formatted the sd card and wrote the json file, thenput it in the ESP32. Went the installer page and connected via the com 6.
Clicked on install and it just keeps saying preparing to install, and periooically locking up. Tried Chrome and Edge browsers. Still the same. Will not install. Help please?

**Comment by xperiments** [comment]
Come on discord where we can help you directly.
Have you installed the drivers?
COM6 .. will depend actually. Needs to be the screen port
