### ISSUE TITLE
Local build and install -> white screen on device

### ISSUE THREAD

**Issue by andypiper** [xperiments-in/xtouch#6]
**Describe the bug**
Building and installing the firmware using PlatformIO and esptool locally results in a white screen on the display.

**To Reproduce**

1. Build the firmware --> success (apart from the post-install steps failing due to not having a webUSB server to upload to)

2. Install to ESP32 e.g. `esptool.py --chip esp32 --port /dev/cu.usbserial-11440 write_flash --erase-all --flash_mode dio --flash_size detect 0x1000 .pio/build/esp32dev/bootloader.bin 0x8000 .pio/build/esp32dev/partitions.bin 0x10000 .pio/build/esp32dev/firmware.bin` --> success

3. Restart --> success

4. Screen is white, but the device is working, the logs show it connecting to Wifi and MQTT and receiving messages.

It works with the correct UI when installed from WebUSB from xperiments site.

**Expected behavior**
A regular xtouch UI should appear.

**XTOUCH:**
 - FW: 0.9.2

**Printers:**
 - Device: X1C

**Comment by leokeba** [comment]
I had the same issue, solved it by replacing "User_Setup.h" in the TFT library by the one provided in the resources folder. Don't know if there is a more straightforward way though.

**Comment by andypiper** [comment]
thank you!
