### ISSUE TITLE
Stuck on "Pair Printer" screen

### ISSUE THREAD

**Issue by kgwatson** [xperiments-in/xtouch#62]
My only P1S appears on the list of printers on my network, but when I try to select it on the "Pair Printer" screen nothing happens so I cannot proceed any futher.

latest xtouch version

P1S
01.04.02.00
1 AMS

**Comment by xperiments** [comment]
I need more info about the specific case but in general:

Is mostly related to:

- You need to select it with the green button
- You have MESH nextwork or unifi ruouter

**Comment by MTCS66** [comment]
The 'pairing printing screen' comes up and shows my X1C and P1S. In the bottom right of the screen the green box is ticked, but when I click on it nothing happens. This is the same, no matter which printer I select.
I dont have a UNIFI router.
The main router is in one room and there is a WIfI booster in the same room as the printers.

Thanks.

**Comment by xperiments** [comment]
Need to check in more depth... Please come to discord

**Comment by MTCS66** [comment]
I've just joined it. How do I contact you on there?

**Comment by Tubbataha** [comment]
With a P1P  it worked first time, then after restarting the printer the assigned IP changed. Now the Pair printer screen shows my printer but when I press the green tick it reboots. In the log I see 
[XTouch][SD] Error Reading JSON File: /xtouch/printer-ips.json
when I check the SD card there is no file of that name
Any suggestions ?

**Comment by Vilunki15** [comment]
I have this same "bug" also. Cant connect to the printer

**Comment by MTCS66** [comment]
I solved my issue, the screen needed to be calibrated.

**Comment by Vilunki15** [comment]
Mine fixed too when recalibrated. I think this could be closed now

**Comment by Vrtule67** [comment]
> Mine fixed too when recalibrated. I think this could be closed now

how I can recalibrate it?
![IMG_20231214_223522](https://github.com/xperiments-in/xtouch/assets/122740952/c29e620f-4f40-4e9f-a055-0f2d56827024)
 when I click to green button then it is rebooted.

**Comment by Vilunki15** [comment]
Remove "XTOUCH" folder from SD card so it resets

**Comment by kevinavos** [comment]
I have tried recalibrating - but have these issues even after recalibrating. Calibrating allowed me to enter the code, but I get stuck after there on the pairing page. I have a wifi6 network. Will head over to discord when I have a moment and can provide logs if necessary.

**Comment by xperiments** [comment]
@kgwatson it only works on 2.4G wifi

**Comment by kevinavos** [comment]
I created an SSID on my network that is only 2.4ghz (with 5ghz disabled) and it fixed it for me.

**Comment by xperiments** [comment]
Great!!

**Comment by Vrtule67** [comment]
Hmm, I still cannot connect my printer with xtouch - in log is error:
_[XTouch][SD] Reading JSON file: /xtouch/printer-ips.json
[XTouch][SD] Error Reading JSON File: /xtouch/printer-ips.json
[ 37218][E][WiFiGeneric.cpp:1578] hostByName(): DNS Failed for null
[ 37232][E][WiFiGeneric.cpp:1578] hostByName(): DNS Failed for null
[ 37240][E][vfs_api.cpp:182] remove(): /xtouch/printer-ips.json does not exists or is directory
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4_

Does somebody have any idea? Is possible create missing file manually? Log saved as attachment.
[esp-web-tools-log.txt](https://github.com/xperiments-in/xtouch/files/13706597/esp-web-tools-log.txt)

**Comment by xperiments** [comment]
@Vrtule67 Come to discord. I think is not related to same issue.
I close

**Comment by doom969** [comment]
> I need more info about the specific case but in general:
> 
> Is mostly related to:
> 
> * You need to select it with the green button
> * You have MESH nextwork or unifi ruouter

I have a similar problem, and I have a unifi router.
What is the issue / fix for unifi routers ?

**Comment by Mr-Savag3** [comment]
Until now, I haven't had a problem with my Unifi Router either. I have a Unifi Dream Router and I'm running fw0.9.58 so I can still use LAN mode... Is there a fix for this? I haven't had an issue at all until now, randomly

**Comment by xperiments** [comment]
I am out for vacation, so i cant help too much. Unifi routers has a lot of
problems. But users reported to solve It. Enter discord server, there IS a
Channel router problems. There are pinned messges. Check that first
