### ISSUE TITLE
Chamber Temp Setting not saved after reboot / left overnight

### ISSUE THREAD

**Issue by hewfish** [xperiments-in/xtouch#64]
**Describe the bug**
In the user interface, enable chamber temp in settings. Leave printer overnight and setting is lost on some kind of reboot / crash restart.

**To Reproduce**
In Settings, enable chamber temp, all working. Leave printer overnight with x-Touch running and on looking in the morning the screen is at the select printer option. click the tick to connect and the chamber temp setting has reverted to disabled.

**Expected behavior**
Chamber temp setting is retaing

**XTOUCH (please complete the following information):**
 - FW: v0.9.24

**Printers (please complete the following information):**
 - Device: P1S
-  AMS units: 1

**Comment by xperiments** [comment]
This is mostly because you don't use a fixed IP. And your router reasigned Ip to another device so on connect it will not detect mqtt so it will remove the settings for this printer
