### ISSUE TITLE
Bind ESP32 card to P1S

### ISSUE THREAD

**Issue by mklovell03** [xperiments-in/xtouch#67]
**Describe the bug**
I purchased the ESP32 Arduino LVGL WIFI&Bluetooth  and stepped through the setup and install. Everything works corrrctly to the point that it is searching for printers. I have a P1S that is on the same WiFi. It will not find the P1S. I went through and have manually created the JSON files (printer-pair.json, printer.json) and loaded them on the sdcard under the xtouch diretory. On boot up card connects to tthe wifi, reads these files and it does show up as an avilable printer in the list. Once I click on the green check mark it simply reboots. I will post the logs later today but reviewing them it attempts to read the "printer-ips.json" file and reports an error stating the file is not in the expected directly. I tried to manually create the printer-ips.json file but without know the syntax I know it's in error. Once I manually created the printer-ips.json file and placed it into the xtouch directly on the sdcard, the log reports the file is missing the hostname and deletes it from the folder. The next step is to bind the P1S and ESP32 to my cell hotspot and try it that way to see if it will identify the printer and step through the configuration. I'm trying to figure out what the proper setup of the "printer-ips.json" file should be so I can manually create it. It may be for not anyways since the ESP32 card won't find the printer even though it's on the same wifi network.

**To Reproduce**
1. Go to 'ESP32 card'
2. Click on 'green check mark'
3. ESP32 reboots
4. See error (will post later)

**Expected behavior**
Trying to bind ESP32 to my P1S printer

**Screenshots**
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
[XTouch][SCREEN] Setup
[   663][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x40112bc0 arg=0x3ffbfc70
XTouch][SD] SD Card Type: [XTouch][SD] SDHC
[XTouch][SD] SD Card Size: 29580MB
[XTouch][SD] Reading JSON file: /xtouch/settings.json
[XTouch][SD] Reading JSON file: /xtouch/printer-ips.json
[XTouch][SD] Error Reading JSON File: /xtouch/printer-ips.json
[XTouch][SD] Reading JSON file: /xtouch/printer-pair.json
[XTouch][FS] Checking for touch config
[XTouch][TOUCH] Load from disk
[XTouch][SD] Reading JSON file: /wifi.json
[XTOUCH][CONNECTION] Connecting to WiFi ..
[XTOUCH][CONNECTION] Connected to the WiFi network with IP: 192.168.1.219
[XTouch][SD] Reading JSON file: /xtouch/printer-ips.json
[XTouch][SD] Error Reading JSON File: /xtouch/printer-ips.json
[XTouch][SD] Reading JSON file: /xtouch/printer-pair.json

**XTOUCH (please complete the following information):**
 - FW: Latest version

**Printers (please complete the following information):**
 - Device: [P1S]
 - FW Version [01.04.02.00]
-  AMS units:[0]

**Additional context**

**Comment by xperiments** [comment]
Is something related to you router, come to discord where we can help better in this case. 
In the meanwhile, do this test: COnnect both , printer & screen to a hotspot created w your mobile. And test if is working fine there. Thx!!!
