### ISSUE TITLE
Orca slicer loses connection to printer when xtool is connected

### ISSUE THREAD

**Issue by kencor1** [xperiments-in/xtouch#68]
**Describe the bug**
After I connect to my printer with the xtouch my Orca slicer will lose connection with the printer. As soon as I 
disable the xtouch Orca slicer will connect again.
Orca Slicer Version 1.8.1
**To Reproduce**

I am using Lan Only Mode on the printer.

**XTOUCH:
 - FW: 0.9.24

**Printers (please complete the following information):**
 - Device: P1S
 - FW Version:  01.04.02.00
-  AMS units: 1

**Additional context**

**Comment by xperiments** [comment]
Is a known bug. Check the main readme about the 1.04 bug....
