### ISSUE TITLE
No text on error screen button

### ISSUE THREAD

**Issue by chrism583** [xperiments-in/xtouch#7]
When AMS encounters an error the button on the error popup is blank.  This is occurring on a fresh install of xtouch with a p1p running 1.04 and AMS running .06.32
See screenshot for more information.
![IMG_9367](https://github.com/xperiments-in/xtouch/assets/62962167/70ac5b86-4917-459a-aff1-93b4f83cf409)

**Comment by xperiments** [comment]
What version are you? 0.9.2 fixed this

**Comment by chrism583** [comment]
0.9.1.  Didn't see there was an update already.  Closing and apologies.
