### ISSUE TITLE
"instert sd card" bug

### ISSUE THREAD

**Issue by Vilunki15** [xperiments-in/xtouch#70]
**Describe the bug**
Doesn't recognize the inserted SD card. 

**Expected behavior**
Even if I insert a fully functional SD card, the device says "Insert SD card". I have tried formatting the card many times, with different settings. I have used different buffer sizes and file systems. Nothing helps. The latest attempt is Fat32 and a 32kt buffer. The second SD card only worked on about the tenth attempt. I don't know if this is a real bug, but I know that my SD cards are intact and of good quality.

**XTOUCH (please complete the following information):**
 - Latest

**Comment by xperiments** [comment]
Is mostly a problem of your sd card. Try formatting it w SDFormatter https://www.sdcard.org/downloads/formatter/
A lot of sandisk sd cards fails.

Some users also commented his sd card connectors where dirty. Try to use a contact cleaner...

If need any more help come to discord
