### ISSUE TITLE
Long use of screen disconnects from printer

### ISSUE THREAD

**Issue by php4umagento** [xperiments-in/xtouch#73]
**Describe the bug**
When screen is used 24/7 on some point it disconnects from printer and shows printer selection list
Have 4 screens and all behave same way

**To Reproduce**
1. Leave screen running for over 24hrs
2. Observe printer list

**Expected behavior**
Screen is connected to printer 24/7 unless printer is offline

**XTOUCH (please complete the following information):**
 - FW: 0.9.36

**Printers (please complete the following information):**
 - Device: P1P, P1S
 - FW Version 01.04.02.00

**Comment by xperiments** [comment]
Do you have fixed ips?

This is mostly caused because router changed ip

**Comment by php4umagento** [comment]
Is there any place where screen shows its MAC or IP?

**Comment by php4umagento** [comment]
> Do you have fixed ips?
> 
> This is mostly caused because router changed ip

I will set static and confirm

**Comment by php4umagento** [comment]
Static IP fixed it - thanks
