### ISSUE TITLE
Controller move wrong axis after switching screen.

### ISSUE THREAD

**Issue by derSchrauberlehrling** [xperiments-in/xtouch#74]
**Describe the bug**
The controller moves the Z-axis under the following conditions, even though I intend to move the Y-axis. After a Z-axis movement (only the upper and lower arrows appear on the display), you need to return to the home screen. Then, switch back to the Movement screen. On my screen, 5 buttons appear: Up, Down, Left, Right, and Home. On Left and Right, the X-axis moves as desired. However, on Up and Down, the Z-axis moves. As soon as I click the (XY - Z) toggle button, the screen remains the same (5 buttons). However, now the XY movement is restored as usual.

**To Reproduce**
**Steps to reproduce the behavior:**
 Go to the movement screen and switch to Z-axis movement.
 After moving the Z-axis, click on the home screen.
 Go back to the Movement screen, which appears with XY-move settings.
 Instead of Y, the up and down buttons move the Z-axis.

**Expected behavior**
I would expect two separate Movement screens, each with one functionality.
One for XY-movement and one for Z-movement only.

**XTOUCH:**
FW: 0.9.37

**Printers:**
Device: Bambulab P1S
FW Version: 01.04.02.00
AMS units: 1

Thank you very much for your work!!!

**Comment by xperiments** [comment]
I think y have not understand how it works

Actually you have 2 screens
- One that controls X/Y
- One that controls Z

You can switch between the 2 screen with the top right icon
