### ISSUE TITLE
Enable display time out during printing

### ISSUE THREAD

**Issue by heelsmj** [xperiments-in/xtouch#75]
## Feature Description

I often leave the printer printing for multiple hours and overnight. It would be nice if the display turned off while it was printing.

## Justification
I imagine I’m not the only one that would benefit from this

## Suggested Implementation (if you have one)

Maybe just include a toggle next to the timeout slider to enable or disable timeout during printing

## Screenshots or Examples (if applicable)

[Attach screenshots or examples if relevant]

**Comment by xperiments** [comment]
Closed in next release
