### ISSUE TITLE
Unable to build using PlatformIO IDE (VSCode)

### ISSUE THREAD

**Issue by MaximeLussier** [xperiments-in/xtouch#76]
**Describe the bug**
I am unable to build with a clean checkout.

**To Reproduce**
1. Clean Checkout
2. Open in VSCode with PlatformIO IDE
3. Build

**Expected behavior**
For it to build...

**Screenshots**
![image](https://github.com/xperiments-in/xtouch/assets/944488/b7cb7992-cf6b-4149-90cb-ce3c6948934d)
![image](https://github.com/xperiments-in/xtouch/assets/944488/b956dd94-b861-495f-846a-ff5f40d7ea16)

**XTOUCH (please complete the following information):**
 - Checkout of MAIN

**Printers (please complete the following information):**
 - Device: P1S
 - FW Version MAIN
-  AMS units: 1

**Additional context**
Thanks for the awesome project! Trying to port on SC01 Plus, having it working on the recommended hw presently (web installer)
If I get it working on both boards (no regression...) I will contribute back

**Comment by xperiments** [comment]
I am sorry but I don't provide support for compile as actually is a lot tied on my computer. Feel free to enter discord and ask in the os-code-help channel https://discord.com/channels/1144016315548438600/1158808917367865344

**Comment by MaximeLussier** [comment]
Ok, thank! I managed to build but the lv_conf.h file should probably be managed better using LV_CONF_PATH or LV_CONF_INCLUDE_SIMPLE

**Comment by MaximeLussier** [comment]
I've managed to port XTouch to the SC01 Plus (3.5" Capacitive). There are a few glitches to correct but it works.
The firmware bug with the P1S is preventing 2 XTouch from working at the same time :(

**Comment by MaximeLussier** [comment]
@xperiments Je semble pas avoir accès au Discord...

**Comment by xperiments** [comment]
https://discord.gg/Jdvp5CShnt
