### ISSUE TITLE
Issue with first setup - Wifi error

### ISSUE THREAD

**Issue by ALEX-9-99** [xperiments-in/xtouch#8]
**Describe the bug**
I did the setup process, but the device cant connect to my P1P.
After setting up the software, the device is stuck in a connection loop
- cant find printer

I Added the log file with the error

--- It probably is connected with my ongoing print. I will retest afterwards, but i could't find anything about the error -----

**To Reproduce**
Set wifi.json
Ran the Setup process

**Expected behavior**
Finding my printer on the network and connecting to it.

**XTOUCH (please complete the following information):**
 - FW: [e.g. 1.0.0]

**Printers (please complete the following information):**
 - Device: P1P
 - FW Version 1.04.01
-  AMS units: 1

**Additional context**
[esp-web-tools-logs (3).txt](https://github.com/xperiments-in/xtouch/files/12813525/esp-web-tools-logs.3.txt)

**Comment by xperiments** [comment]
Have you read the docs?

https://github.com/xperiments-in/xtouch#troubleshooting

Can you please try to change the timeout and check if doing this works for you?

I close by now. Feel free to reopen it if needed. Thx
