### ISSUE TITLE
ESP32 2432S022 board touch error

### ISSUE THREAD

**Issue by cosmos1978** [xperiments-in/xtouch#80]
**Describe the bug**
I get this error on startup using a slightly different board (esp32 2432S022)
This board has a capacitive touch screen.

ELF file SHA256: b5a9d87e0c1e0a9d

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
[XTouch][SCREEN] Setup
[   657][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x401133cc arg=0x3ffbfd00
XTouch][SD] SD Card Type: [XTouch][SD] SDHC
[XTouch][SD] SD Card Size: 29608MB
[XTouch][SD] Reading JSON file: /xtouch/settings.json
[XTouch][SD] Reading JSON file: /xtouch/printer-ips.json
[XTouch][SD] Error Reading JSON File: /xtouch/printer-ips.json
[XTouch][SD] Reading JSON file: /xtouch/printer-pair.json
[XTouch][SD] Error Reading JSON File: /xtouch/printer-pair.json
[XTouch][FS] Checking for touch config
[XTouch][TOUCH] Touch Setup
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400f5d1a  PS      : 0x00060230  A0      : 0x800d2804  A1      : 0x3ffb2140  
A2      : 0x00000000  A3      : 0x88c00000  A4      : 0x00000000  A5      : 0x00ef013f  
A6      : 0xffffffff  A7      : 0x3ffcb068  A8      : 0x800f5d1a  A9      : 0x3ffb2120  
A10     : 0x000002cd  A11     : 0x00000001  A12     : 0x00000000  A13     : 0x00000000  
A14     : 0x000002cd  A15     : 0x00000000  SAR     : 0x0000000a  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000004  LBEG    : 0x40084815  LEND    : 0x4008481d  LCOUNT  : 0x00000027  

Backtrace: 0x400f5d17:0x3ffb2140 0x400d2801:0x3ffb2160 0x400f3d12:0x3ffb2190 0x400e72df:0x3ffb21b0 0x400f5c9c:0x3ffb2200 0x400da8e8:0x3ffb2230 0x400db794:0x3ffb2260 0x40113e7e:0x3ffb2290

**Comment by xperiments** [comment]
Yeah, we don't support it ATM. But I will work on it
