### ISSUE TITLE
Support for ESP32-3248S035

### ISSUE THREAD

**Issue by dayshiers** [xperiments-in/xtouch#9]
## Feature Description

Support for ESP32-3248S035

## Justification

Some sellers on Aliexpress are listing ESP32-2432S028R but shipping out ESP32-3248S035 instead.

**Comment by xperiments** [comment]
Support is only for 2.8 as described in docs since beginning. ESP32-3248S035 is another chip, another touch panel, another resolution.

I am sorry but we will not support this version.
