### ISSUE TITLE
Cannot update/change any temps on x1c

### ISSUE THREAD

**Issue by bcarriveau** [xperiments-in/xtouch#92]
Esp32-2432s028r

XTOUCH ver 0.9.58

**Describe the bug**
When trying to change temps, Cannot do so. It consistently refreshes? 

**To Reproduce**
Boot esp32

Connect to printer

Select a temperature to change.

**Expected behavior**

Enter a desired value 0-100 and allow it to update properly. 

**Printers (please complete the following information):**
 - Device: x1C
 - FW Version 01.07.01.00
-  AMS units:00.00.06.40

https://github.com/xperiments-in/xtouch/assets/60801063/c9ea2249-8ea9-4a59-a578-950d682c262f

**Comment by xperiments** [comment]
This was fixed
